version: "3.8"

services:
  database:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: price_guessing
      POSTGRES_USER: price_guessing_user
      POSTGRES_PASSWORD: price_guessing_password
    volumes:
      - ./database-persisted-data:/var/lib/postgresql/data

  mqtt-broker:
    image: emqx/emqx:5.8.6
    restart: always
    ports:
      - "1883:1883" # MQTT
      - "18083:18083" # Dashboard
    environment:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: password

  authentication-service:
    build: ./backend/authentication-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: price_guessing_user
      DB_PASSWORD: price_guessing_password
      DB_NAME: price_guessing
      JWT_SECRET: secret
      JWT_EXPIRATION_IN_DAYS: 1

    depends_on:
      - database

  price-guessing-service:
    build: ./backend/price-guessing-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: price_guessing_user
      DB_PASSWORD: price_guessing_password
      DB_NAME: price_guessing
      AUTH_COOKIE_NAME: authToken
      JWT_SECRET: secret
      MQTT_URL: mqtt://mqtt-broker:1883

    depends_on:
      - authentication-service
      - database
      - mqtt-broker

  btc-usd-tracker:
    build: ./backend/price-tracker-service
    restart: always
    environment:
      DATABASE_URL: postgresql://price_guessing_user:price_guessing_password@database:5432/price_guessing
      MQTT_URL: mqtt://mqtt-broker:1883
      INTERVAL_IN_SECONDS: 15
    depends_on:
      - database
      - mqtt-broker
      - price-guessing-service

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3003:3003"
    environment:
      AUTHENTICATION_SERVICE_ROUTE: http://authentication-service:3000
      API_SERVICE_ROUTE: http://price-guessing-service:3001
      AUTH_COOKIE_NAME: authToken
    depends_on:
      - database
      - mqtt-broker
      - authentication-service
      - btc-usd-tracker
      - price-guessing-service
